//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneOtamasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int Personel_Id { get; set; }
        public string Personel_Ad { get; set; }
        public string Personel_Soyad { get; set; }
        public string Personel_Tc { get; set; }
        public string Persone_Tel { get; set; }
        public string Personel_Mail { get; set; }
        public string Personel_Adres { get; set; }
        public string Personel_KullaniciAdi { get; set; }
        public string Personel_Sifre { get; set; }
        public string Personel_Cinsiyet { get; set; }
    }
}
